import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "../_components/sidebar/Sidebar.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "dashboard-products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-[1]">
        <Sidebar/>
        <div className="ml-5 flex-[6]">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
